build:
  image: golang
  environment:
    - CODECOV_TOKEN=$$CODECOV_TOKEN
  commands:
    - go get
    - go build
    - go test -cover -v -coverprofile=coverage.txt -covermode=atomic
    - curl -sSL https://codecov.io/bash | bash
